logging:
  level:
    org:
      springframework: info

spring:
  application:
    name: weather-prediction-service
  config:
    import: optional:configserver:http://localhost:8888

#      type: [main],[weather],[clouds],[wind],[wind],[visibility],[pop],[rain],[snow]
#      operation: lt,gt,eq
#      parameter: [value]
#      message: [String]



